# Generated by Django 5.0.1 on 2026-03-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkresult",
            name="quality_score",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="checks.qualityscore",
            ),
        ),
    ]
