# Generated by Django 4.2.29 on 2026-03-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("threshold", models.IntegerField(default=80)),
                ("is_alert_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="alert_config", to="datasets.dataset"
                    ),
                ),
            ],
            options={
                "db_table": "alert_configs",
            },
        ),
    ]
