# Generated by Django 5.0.1 on 2026-03-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_alertconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertconfig",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
