# Generated by Django 4.2.29 on 2026-03-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("schedule", "0003_alertconfig_email_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="periodic_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_schedule",
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
