#!/bin/bash
set -euo pipefail

# =============================================================
# DataPulse Dev EC2 Bootstrap
# Runs once on first launch. Re-runs are idempotent.
# =============================================================

AWS_REGION="${aws_region}"
SSM_PREFIX="${ssm_prefix}"
REPO_URL="https://github.com/${github_repo}.git"
GIT_BRANCH="${git_branch}"
APP_DIR="/opt/datapulse"
GITHUB_TOKEN="${github_token}"

# -----------------------------------------------------------
# Helpers
# -----------------------------------------------------------
log() { echo "[$(date '+%H:%M:%S')] $*"; }

ssm_get() {
  aws ssm get-parameter \
    --name "$SSM_PREFIX/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "$AWS_REGION"
}

# -----------------------------------------------------------
# System packages
# -----------------------------------------------------------
log "Installing packages..."
dnf update -y
dnf install -y docker git aws-cli jq

# Docker
systemctl enable docker
systemctl start docker
usermod -aG docker ec2-user

# Docker Compose v2 plugin - latest version
log "Installing Docker Compose..."
COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest \
  | jq -r '.tag_name')
mkdir -p /usr/local/lib/docker/cli-plugins
curl -SL "https://github.com/docker/compose/releases/download/$${COMPOSE_VERSION}/docker-compose-linux-x86_64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

# Docker Buildx plugin - latest version
log "Installing Docker Buildx..."
BUILDX_VERSION=$(curl -s https://api.github.com/repos/docker/buildx/releases/latest \
  | jq -r '.tag_name')
curl -SL "https://github.com/docker/buildx/releases/download/$${BUILDX_VERSION}/buildx-$${BUILDX_VERSION}.linux-amd64" \
  -o /usr/local/lib/docker/cli-plugins/docker-buildx
chmod +x /usr/local/lib/docker/cli-plugins/docker-buildx

# Verify installations
log "Verifying Docker tools..."
docker --version
docker compose version
docker buildx version

# -----------------------------------------------------------
# Clone repo and checkout specific branch
# -----------------------------------------------------------
log "Cloning repo and checking out $GIT_BRANCH branch..."
if [ ! -d "$APP_DIR/.git" ]; then
  if [ -n "$GITHUB_TOKEN" ]; then
    # Use token for private repos
    git clone "https://$GITHUB_TOKEN@github.com/${github_repo}.git" "$APP_DIR"
  else
    # Public repo
    git clone "$REPO_URL" "$APP_DIR"
  fi
  git -C "$APP_DIR" checkout "$GIT_BRANCH"
else
  log "Repo already cloned — fetching and checking out $GIT_BRANCH"
  git -C "$APP_DIR" fetch origin
  git -C "$APP_DIR" checkout "$GIT_BRANCH"
  git -C "$APP_DIR" pull origin "$GIT_BRANCH"
fi

# -----------------------------------------------------------
# Pull secrets from SSM and write .env
# -----------------------------------------------------------
log "Fetching secrets from SSM..."

POSTGRES_USER=$(ssm_get postgres_user)
POSTGRES_PASSWORD=$(ssm_get postgres_password)
POSTGRES_DB=$(ssm_get postgres_db)
ANALYTICS_USER=$(ssm_get analytics_user)
ANALYTICS_PASSWORD=$(ssm_get analytics_password)
ANALYTICS_DB=$(ssm_get analytics_db)
SECRET_KEY=$(ssm_get secret_key)
GRAFANA_USER=$(ssm_get grafana_user)
GRAFANA_PASSWORD=$(ssm_get grafana_password)
DJANGO_SETTINGS_MODULE=$(ssm_get django_settings_module)

cat > "$APP_DIR/.env" <<ENV
# Auto-generated by EC2 userdata — do not edit manually
# Re-generated on every start via datapulse.service

POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB

ANALYTICS_USER=$ANALYTICS_USER
ANALYTICS_PASSWORD=$ANALYTICS_PASSWORD
ANALYTICS_DB=$ANALYTICS_DB
TARGET_DB_URL=postgresql://$ANALYTICS_USER:$ANALYTICS_PASSWORD@db-analytics:5432/$ANALYTICS_DB

SECRET_KEY=$SECRET_KEY
DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
DEBUG=True
GUNICORN_WORKERS=2
GUNICORN_THREADS=2
GUNICORN_LOG_LEVEL=info

GRAFANA_USER=$GRAFANA_USER
GRAFANA_PASSWORD=$GRAFANA_PASSWORD

EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
DEFAULT_FROM_EMAIL=noreply@datapulse.com
EMAIL_HOST=localhost
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=

NEXT_PUBLIC_API_URL=http://localhost:8000
ENV

chmod 600 "$APP_DIR/.env"
chown ec2-user:ec2-user "$APP_DIR/.env"

# -----------------------------------------------------------
# Systemd service — keeps the stack running across reboots
# and restarts it cleanly on scheduler start cycles
# -----------------------------------------------------------
log "Registering systemd service..."
cat > /etc/systemd/system/datapulse.service <<SERVICE
[Unit]
Description=DataPulse Dev Stack
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$APP_DIR
User=ec2-user
Group=ec2-user

# Re-fetch secrets on every start so rotated creds are picked up
ExecStartPre=/bin/bash -c 'AWS_REGION=${aws_region} SSM_PREFIX=${ssm_prefix} source $APP_DIR/scripts/refresh-env.sh'

# Build and start services
ExecStart=/bin/bash -c 'docker compose build && docker compose --profile all up -d'

ExecStop=/usr/local/lib/docker/cli-plugins/docker-compose down

[Install]
WantedBy=multi-user.target
SERVICE

# Separate script to refresh .env without re-running full userdata
mkdir -p "$APP_DIR/scripts"
cat > "$APP_DIR/scripts/refresh-env.sh" <<'REFRESH'
#!/bin/bash
set -euo pipefail

ssm_get() {
  aws ssm get-parameter \
    --name "$SSM_PREFIX/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "$AWS_REGION"
}

POSTGRES_USER=$(ssm_get postgres_user)
POSTGRES_PASSWORD=$(ssm_get postgres_password)
POSTGRES_DB=$(ssm_get postgres_db)
ANALYTICS_USER=$(ssm_get analytics_user)
ANALYTICS_PASSWORD=$(ssm_get analytics_password)
ANALYTICS_DB=$(ssm_get analytics_db)
SECRET_KEY=$(ssm_get secret_key)
GRAFANA_USER=$(ssm_get grafana_user)
GRAFANA_PASSWORD=$(ssm_get grafana_password)
DJANGO_SETTINGS_MODULE=$(ssm_get django_settings_module)

cat > /opt/datapulse/.env <<ENV
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
ANALYTICS_USER=$ANALYTICS_USER
ANALYTICS_PASSWORD=$ANALYTICS_PASSWORD
ANALYTICS_DB=$ANALYTICS_DB
TARGET_DB_URL=postgresql://$ANALYTICS_USER:$ANALYTICS_PASSWORD@db-analytics:5432/$ANALYTICS_DB
SECRET_KEY=$SECRET_KEY
DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
DEBUG=True
GUNICORN_WORKERS=2
GUNICORN_THREADS=2
GUNICORN_LOG_LEVEL=info
GRAFANA_USER=$GRAFANA_USER
GRAFANA_PASSWORD=$GRAFANA_PASSWORD
EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
DEFAULT_FROM_EMAIL=noreply@datapulse.com
EMAIL_HOST=localhost
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
NEXT_PUBLIC_API_URL=http://localhost:8000
ENV
chmod 600 /opt/datapulse/.env
REFRESH

chmod +x "$APP_DIR/scripts/refresh-env.sh"
chown -R ec2-user:ec2-user "$APP_DIR"

systemctl daemon-reload
systemctl enable datapulse

log "Bootstrap complete. Starting DataPulse stack..."
systemctl start datapulse

# Show final status
sleep 15
log "Final status:"
systemctl status datapulse --no-pager
su - ec2-user -c "cd $APP_DIR && docker ps"
