# Generated by Django 4.2.29 on 2026-03-11 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("triggered_by", models.CharField(max_length=255)),
                (
                    "trigger_type",
                    models.CharField(choices=[("manual", "Manual"), ("scheduled", "Scheduled")], max_length=20),
                ),
                ("score", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="datasets.dataset"
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
